name: Bitcoin Monte Carlo Simulation

on:
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    name: Run Monte Carlo Simulation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run simulation
        run: cargo run --release -- --coin bitcoin --simulations 10000 --steps 7
